title:             Tony's Personal Website
email:             lchabolla@gmail.com
description:       Tony Chabolla's personal site where his projects and tech ideas will be posted.
author:            Luis "Tony" Chabolla, Jr.
baseurl:           "" # Leave this alone if this is your main site (i.e. username.github.io). If instead this is a site for a project, e.g. username.github.io/
url:               "http://lchabolla.github.io" # or http://username.github.io/mycleverproject if it is a project site, or http://mylovelydomainname.com if you have a domain, and so on.

collections:
  pages:
    output: true
    permalink: /:name

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
